#!/usr/bin/env bash

if [[ -z "$3" ]]
then
	echo 'Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY'
else
	echo "scp StrictHostKeyChecking=no -i $4 $1 $3@$2:/"
	scp StrictHostKeyChecking=no -i $4 $1 $3@$2:/
fi
