#!/usr/bin/env bash

sudo su

apt-get update -y
apt-get install nginx -y
apt-get install curl -y
sudo chown -R  $USER:$USER /var/www
chmod 777 /var/www/html/index.nginx-debian.html
echo "Hello World!" > /var/www/html/index.nginx-debian.html

systemctl restart nginx
