#!/usr/bin/env bash

sudo apt-get update -y
sudo apt-get install nginx -y

sudo ufw allow 'Nginx HTTP'

apt-get install curl -y

chmod 777 /var/www/html/index.nginx-debian.html
echo "Hello World!" > /var/www/html/index.nginx-debian.html

systemctl restart nginx
