#!/usr/bin/env bash

IMAGE_NAME="holbertonschool/265-0"
COMMAND="/bin/bash"

# Find the container ID or name
CONTAINER_ID=$(docker ps --filter ancestor=$IMAGE_NAME --format "{{.ID}}")

if [ -n "$CONTAINER_ID" ]; then
    docker exec -d $CONTAINER_ID service apache2 start
else
    echo "No running containers found for image: $IMAGE_NAME"
fi
